# Copyright 2021 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create gcloud Service Account
  shell: gcloud iam service-accounts create "{{ gcloud_preq_sa_name }}" --project="{{ project_id }}"
  ignore_errors: yes 

- name: Generate and download gcloud Service Account Key
  shell: >
    gcloud iam service-accounts keys create "{{ gcloud_preq_sa_name }}".json
    --iam-account="{{ gcloud_preq_sa_name }}@{{ project_id }}.iam.gserviceaccount.com"
    --project="{{ project_id }}"
  ignore_errors: yes   

- name: Create directory for GCP Keys if it does not exist
  ansible.builtin.file:
    path: "{{ gcp_sa_key_dir }}"
    state: directory

- name: Move GCR Service Account key file
  shell: mv "{{ gcloud_preq_sa_name }}".json "{{ gcp_sa_key_dir }}"
  ignore_errors: yes 

- name: Grant compute.viewer role to gcloud Service Account
  shell: >
    gcloud projects add-iam-policy-binding "{{ project_id }}"
    --member="serviceAccount:{{ gcloud_preq_sa_name }}@{{ project_id }}.iam.gserviceaccount.com"
    --role="roles/compute.viewer"
  ignore_errors: yes   

- name: Grant resourcemanager.projectIamAdmin role to gcloud Service Account
  shell: >
    gcloud projects add-iam-policy-binding "{{ project_id }}"
    --member="serviceAccount:{{ gcloud_preq_sa_name }}@{{ project_id }}.iam.gserviceaccount.com"
    --role="roles/resourcemanager.projectIamAdmin"
  ignore_errors: yes 

- name: Grant iam.serviceAccountAdmin role to gcloud Service Account
  shell: >
    gcloud projects add-iam-policy-binding "{{ project_id }}"
    --member="serviceAccount:{{ gcloud_preq_sa_name }}@{{ project_id }}.iam.gserviceaccount.com"
    --role="roles/iam.serviceAccountAdmin"
  ignore_errors: yes   

- name: Grant iam.serviceAccountKeyAdmin role to gcloud Service Account
  shell: >
    gcloud projects add-iam-policy-binding "{{ project_id }}"
    --member="serviceAccount:{{ gcloud_preq_sa_name }}@{{ project_id }}.iam.gserviceaccount.com"
    --role="roles/iam.serviceAccountKeyAdmin"
  ignore_errors: yes   

- name: Grant serviceusage.serviceUsageAdmin role to gcloud Service Account
  shell: >
    gcloud projects add-iam-policy-binding "{{ project_id }}"
    --member="serviceAccount:{{ gcloud_preq_sa_name }}@{{ project_id }}.iam.gserviceaccount.com"
    --role="roles/serviceusage.serviceUsageAdmin"
  ignore_errors: yes   

- name: Recursively change ownership of GCP Key directory
  ansible.builtin.file:
    path: "{{ gcp_sa_key_dir }}"
    state: directory
    recurse: yes
    owner: "{{ login_user }}"
    group: "{{ login_user_group }}"
