# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: "[acm] Disable ACM"
  ansible.builtin.command:
    argv:
      - gcloud
      - beta
      - container
      - hub
      - config-management
      - unmanage
      - "--membership={{ acm_membership }}"
      - "--project={{ acm_gcpproject }}"
  register: _results
  retries: 5
  delay: 10
  until: _results.rc == 0

- name: "[acm] Remove ACM operator configuration"
  ansible.builtin.command:
    argv:
      - kubectl
      - --kubeconfig
      - "{{ yamldestpath }}/{{ uc_name }}-kubeconfig"
      - delete
      - configmanagement
      - --all

- name: "[acm] Remove ACM namespaces"
  ansible.builtin.command:
    argv:
      - kubectl
      - --kubeconfig
      - "{{ yamldestpath }}/{{ uc_name }}-kubeconfig"
      - delete
      - ns
      - config-management-system
      - config-management-monitoring
      - --ignore-not-found

- name: "[acm] Remove ACM operator CRD"
  ansible.builtin.command:
    argv:
      - kubectl
      - --kubeconfig
      - "{{ yamldestpath }}/{{ uc_name }}-kubeconfig"
      - delete
      - crd
      - configmanagements.configmanagement.gke.io
      - --ignore-not-found

