# Copyright 2022 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: "[uc] Sanity Checks"
  ansible.builtin.assert:
    that:
      - yamldestpath | length >= 6
      - sakeyfolder_base is defined
      - uc_name | length >= 3
      - uc_nw_ipallocmode is search("dhcp") or uc_nw_ipallocmode is search("static")
      - uc_nw_gw | length >= 7
      - uc_nw_nm | length >= 7
      - uc_nw_dns is defined and uc_nw_dns | type_debug == "list"
      - uc_nw_servicecidr | length >= 7
      - uc_nw_podcidr | length >= 7
      - uc_nw_ntp is defined and uc_nw_ntp | type_debug == "list"
      - uc_nw_searchdomains is defined and uc_nw_searchdomains | type_debug == "list"
      - uc_ipblock_netmask | length >= 7
      - uc_ipblock_gateway | length >= 7
      - uc_lb_kind is search("MetalLB")
      - uc_ipblock_ips is defined and uc_ipblock_ips | type_debug == "list"
      - uc_lb_vips_cp | length >= 7
      - uc_masternode_cpus | int
      - uc_masternode_mem | int
      - uc_antiaffinitygroups == uc_antiaffinitygroups|bool
      - uc_stackdriver_projectid | length >= 6
      - uc_stackdriver_clusterlocation | length >= 6
      - uc_stackdriver_enablevpc == uc_stackdriver_enablevpc|bool
      - logging_monitoring_gcpsa_path | length >= 6
      - uc_stackdriver_disablevsphereresourcemetrics == uc_stackdriver_disablevsphereresourcemetrics|bool
      - uc_gkeconnect_projectid | length >= 6
      - connect_register_gcpsa_path | length >= 6
      # - uc_cloudauditlogging_projectid | length >= 6
      # - uc_cloudauditlogging_clusterlocation | length >= 6
      # - audit_logging_gcpsa_path | length >= 6
      - uc_autorepair == uc_autorepair|bool
    fail_msg: "Undefined variables."
    success_msg: "All required variables are defined."

- name: "[uc] Note on optional values"
  ansible.builtin.debug:
    msg: "Optional values uc_vc_folder, uc_nodepools_vsphere_tags_category, uc_nodepools_vsphere_tags_name are not checked. Please double check if required." # noqa 204
