# Copyright 2022 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: "[uc] Clean up old SSH host keys from incomplete runs"
  ansible.builtin.file:
    path: "/home/ubuntu/.ssh/known_hosts"
    state: absent

- name: "[uc] Include tasks - asserts.yml"
  include_tasks: asserts.yml

- name: "[uc] Check for existing cluster kubeconfig"
  ansible.builtin.stat:
    path: "~/{{ uc_kubeconfig }}"
  register: uc_kubeconfig_file

- name: "[uc] Check if existing API server is up"
  ansible.builtin.command:
    argv:
      - kubectl
      - --kubeconfig
      - "{{ uc_kubeconfig }}"
      - cluster-info
  when:
    - uc_kubeconfig_file.stat.exists
    - uc_install|default(false)|bool
  changed_when: false

- name: "[uc] Search Admin Cluster for User Cluster namespaces"
  command:
    argv:
      - kubectl
      - --kubeconfig
      - kubeconfig
      - get
      - ns
      - -o
      - name
  register: uc_namespaces
  when:
    - not uc_install|default(false)|bool

- name: "[uc] Include tasks - install.yml"
  include_tasks: install.yml
  when: 
    - uc_install|default(false)|bool
    - not uc_kubeconfig_file.stat.exists

# updating cluster settings
- name: "[uc] Include tasks - update.yml"
  include_tasks: update.yml
  when: 
    - uc_install|default(false)|bool
    - uc_kubeconfig_file.stat.exists
    - not uc_upgrade|default(false)|bool

# version updates and upgrades
- name: "[uc] Include tasks - upgrade.yml"
  include_tasks: upgrade.yml
  when: 
    - uc_install|default(false)|bool
    - uc_kubeconfig_file.stat.exists
    - uc_upgrade|default(false)|bool

- name: "[uc] Include tasks - uninstall.yml"
  include_tasks: uninstall.yml
  when:
    - not uc_install|default(false)|bool
    - uc_kubeconfig_file.stat.exists
    - uc_namespaces is search(uc_name)
