# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  match:
    - excludedNamespaces:
        - anthos-identity-service
        - asm-ingress
        - asm-system
        - config-management-monitoring
        - config-management-system
        - gatekeeper-system
        - gke-connect
        - gke-system
        - istio-system
        - kube-node-lease
        - kube-system
        - resource-group-system
      processes: ["audit", "webhook", "sync","mutation-webhook"]
  sync:
    syncOnly:
      # Required for CIS namespaces require network policies
      - group: "networking.k8s.io"
        version: "v1"
        kind: "NetworkPolicy"
