# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "[ais] Block - Copy GCP SA files, upload login config to GCS, clean up"
  block:
    - name: "[ais] Copy sensitive files"
      ansible.builtin.include_role:
        name: copy_credentials
      vars:
        is_ais: true

    - name: "[ais] Switch Google Service Account"
      ansible.builtin.command: # noqa 305 301 no-changed-when
        argv:
          - gcloud
          - auth
          - activate-service-account
          - --key-file
          - "{{ job_sakeyfolder }}/{{ ais_gcpsa_path }}"

    - name: "[ais] Upload login config file"
      ansible.builtin.command:
        argv:
          - gsutil
          - cp
          - "{{ [yamldestpath, ais_login_config_file] | join('/') }}"
          - "{{ ais_gcsbucket }}/{{ uc_name if uc_name is defined else ac_name }}/{{ ais_login_config_file }}"

  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    http_proxy: "{{ glb_proxyurl }}"
    https_proxy: "{{ glb_proxyurl }}"
    no_proxy: "{{ glb_noproxy }}"

  always:
    - name: "Include role to delete sensitive files"
      ansible.builtin.include_role:
        name: cleanup
