# Copyright 2022 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: "[cleanup] Find GCP SA JSON files on admin workstation"
  find:
    paths: ["{{ yamldestpath }}"]
    file_type: file
    pattern: '*.json'
  register: jsonfiles

# only runs when JSON files are present
- name: "[cleanup] Clean up GCP SA JSON files on admin workstation"
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ jsonfiles.files }}"
  when: jsonfiles.files is defined

- name: "[cleanup] Find *credential*.yaml files on admin workstation"
  find:
    path: "{{ yamldestpath }}"
    file_type: file
    pattern: '*credential*.yaml'
  register: credyamlfiles

# only runs when *credential*.yaml files are present
- name: "[cleanup] Clean up *credential*.yaml on admin workstation"
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ credyamlfiles.files }}"
  when: credyamlfiles.files is defined

- name: "[cleanup] Find *credential*.yaml files on admin workstation in admin cluster subfolder"
  find:
    path: "{{ yamldestpath }}/{{ ac_name }}"
    file_type: file
    pattern: '*credential*.yaml'
  register: credyamlfiles
  when:
  - ac_name is defined
  - ac_name | length > 0

# only runs when *credential*.yaml files are present in admin cluster subfolder
- name: "[cleanup] Clean up *credential*.yaml on admin workstation in admin cluster subfolder"
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ credyamlfiles.files }}"
  when:
  - credyamlfiles.files is defined

- name: "[cleanup] Find *credential*.yaml files on admin workstation in user cluster subfolder"
  find:
    path: "{{ yamldestpath }}/{{ uc_name }}"
    file_type: file
    pattern: '*credential*.yaml'
  register: credyamlfiles
  when:
  - uc_name is defined
  - uc_name | length > 0

# only runs when *credential*.yaml files are present in user cluster subfolder
- name: "[cleanup] Clean up *credential*.yaml on admin workstation in user cluster subfolder"
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ credyamlfiles.files }}"
  when: 
  - credyamlfiles.files is defined

- name: "[cleanup] Delete temp directory created for ASM files"
  file:
    path: "{{ asm_temp }}"
    state: absent
  when:
    - (asm_temp is defined) and (asm_temp | length > 0)
    - not (asm_debug_mode|default(false)|bool)

