# Copyright 2022 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "[cleanup] Include tasks - asserts.yml"
  include_tasks: asserts.yml
  when: ac_name is defined or uc_name is defined or adminws_name is defined

- name: "[cleanup] Set folder name for GCP SA JSON key files"
  ansible.builtin.set_fact:
    job_sakeyfolder: "{{ sakeyfolder_base }}-{{ ac_name if ac_name is defined else uc_name if uc_name is defined else adminws_name if adminws_name is defined else 'upload' }}"
    
- name: "[cleanup] Clean up GCP SA JSON files on jumphost"
  file:
    path: "{{ job_sakeyfolder }}"
    state: absent

- name: "[cleanup] Clean up sensitive files on jumphost"
  include_tasks: adminws.yml
  when: adminws_name is defined

- name: "[cleanup] Clean up sensitive file on admin workstation"
  include_tasks: clusters.yml
  when:
  - (ac_name is defined and ac_name | length > 0) or
    (uc_name is defined and uc_name | length > 0) or
    (acm_membership is defined and acm_membership | length > 0)
