apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: busybox
    image: busybox:1.34
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: secret-data
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secret-data
    secret:
      secretName: literal-token