apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-2
spec:
  serviceAccountName: ${K8S_SERVICEACCOUNT}
  containers:
  - name: busybox
    image: busybox:1.34
    args:
    - sleep
    - "1000000"
    volumeMounts:
    - name: secret-data
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secret-data
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "workload-1-secrets"