# Copyright 2021 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
 - name: "Check if DOCKER is installed"
   package_facts:
     manager: "auto"
 - name: "Is docker found?"
   debug:
     msg: "Docker found"
   when: "'docker.io' in ansible_facts.packages"
 - name: "Is docker NOT found?"
   fail:
     msg: "Docker NOT found"
   when: "'docker.io' not in ansible_facts.packages"

 - name: "Check if GCLOUD is installed"
   package_facts:
     manager: "auto"
 - name: "Is gcloud found?"
   debug:
     msg: "gcloud found"
   when: "'google-cloud-sdk' in ansible_facts.packages"
 - name: "Is gcloud NOT found?"
   fail:
     msg: "gcloud NOT found"
   when: "'google-cloud-sdk' not in ansible_facts.packages"


 - name: "checking disk space"
   command: df -h /
   register: space

 - name: "ENSURE YOU HAVE 50GB 'Avail' SPACE ON DISK"
   debug:
    var: space.stdout_lines

# below is good for debugging, uncomment and grep output for `docker` to figure out name
#- name: Print the package facts
#  ansible.builtin.debug:
#    var: ansible_facts.packages
