# Copyright 2021 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create bmctl workspace cluster directory
  ansible.builtin.file:
    path: "{{ login_user_home }}/{{ bmctl_workspace_dir }}/{{ cluster_name }}"
    state: directory
    owner: "{{ login_user }}"
    group: "{{ login_user_group }}"
  tags: [preflight-admin,preflight-hybrid,preflight-user,create-admin,create-hybrid,create-user]

- name: Check if cluster config file exists
  stat:
    path: "{{ login_user_home }}/{{ bmctl_workspace_dir }}/{{ cluster_name }}/{{ cluster_name }}.yaml"
  register: cluster_file_check

- name: Print Message In Case of Creation of Service Accounts is skipped
  ansible.builtin.debug:
    msg: "Creation of Service Accounts for Anthos will be skipped because the anthos cluster configuartion file is already present. If default cluster configuration file is present, then execute create anthos script to update the cluster configuration file."
  when: cluster_file_check.stat.exists == True

- name: Enabling APIs and Creating Service Accounts
  shell:
    cmd: |
      export GOOGLE_APPLICATION_CREDENTIALS="{{ gcp_sa_key_dir }}/{{ gcloud_preq_sa_name }}.json"
      bmctl create config -c "{{ cluster_name }}" --enable-apis --create-service-accounts --project-id="{{ project_id }}"
    chdir: "{{ login_user_home }}"
  when: cluster_file_check.stat.exists == False
  register: check_task_status

- name: Print Message In Case of Creation of Service Accounts
  ansible.builtin.debug:
     msg: "Service Accounts for Anthos has been created. Kindly note that the current cluster configuration file is a default one. Execute create anthos script to update the cluster configuration file."
  when: check_task_status.changed
